name: flutter_app
description: A new Flutter project
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 3.4.0
  firebase_messaging: 15.1.0
  http: ^0.13.3
  provider: ^6.0.3
  google_maps_flutter: ^2.1.1
  geolocator: ^11.0.0
  intl: ^0.17.0
  file_picker: ^5.0.1
  sliding_up_panel: ^2.0.0
  fl_chart: ^0.40.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  assets:
  - assets/common/
  - assets/user/
  - assets/driver/
